# Generated by Django 4.1.5 on 2023-02-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=255)),
                ("order_product", models.CharField(max_length=255)),
                ("order_type", models.CharField(max_length=255)),
                ("order_target", models.CharField(max_length=255)),
                (
                    "operator_provisioning_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not started"),
                            (1, "Started"),
                            (2, "Failed"),
                            (3, "Ready"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "odoo_provisioning_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not started"),
                            (1, "Started"),
                            (2, "Failed"),
                            (3, "Ready"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "goodsign_provisioning_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not started"),
                            (1, "Started"),
                            (2, "Failed"),
                            (3, "Ready"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "mexmanager_provisioning_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not started"),
                            (1, "Started"),
                            (2, "Failed"),
                            (3, "Ready"),
                        ],
                        default=0,
                    ),
                ),
                ("payload", models.JSONField(blank=True)),
                ("dna_order_id", models.CharField(blank=True, max_length=255)),
                ("completed", models.BooleanField(help_text="Task completed or not..")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
