# Generated by Django 4.1.5 on 2023-02-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="barringData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Operator key"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=256, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=256, verbose_name="Value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="barringMMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Operator key"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=256, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=256, verbose_name="Value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="barringRoaming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Operator key"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=256, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=256, verbose_name="Value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="barringRoamingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Operator key"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=256, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=256, verbose_name="Value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="barringSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Operator key"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=256, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=256, verbose_name="Value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="barringVoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Operator key"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=256, verbose_name="Key"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=256, verbose_name="Value"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="mobileDataCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="mobilePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="mobileProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
                    ),
                ),
                (
                    "datacode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.mobiledatacode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SIM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icc", models.CharField(max_length=256)),
                ("imsi", models.CharField(blank=True, max_length=256)),
                ("puk1", models.CharField(max_length=256)),
                ("puk2", models.CharField(max_length=256)),
                (
                    "acc",
                    models.CharField(
                        blank=True,
                        help_text="Used for DNA. Example: 0100",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "tick",
                    models.CharField(
                        blank=True,
                        help_text="Used for DNA. Example: 220",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "sim_type",
                    models.CharField(
                        blank=True,
                        help_text="Used for DNA. Example: USIM-WPKI-CORP-2F3F",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last modified timestamp"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Initial creation timestamp"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subscriptionVoicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("value", models.CharField(max_length=256)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mobile.carrier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subscriptionDataSpeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Data Speed")),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Download / upload speed",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mobile.carrier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription data speeds",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                (
                    "voicemail_number",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Voicemail Number"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Last modified timestamp"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Initial creation timestamp"
                    ),
                ),
                (
                    "subscription_open_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Subscription open date"
                    ),
                ),
                (
                    "subscription_close_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Subscription close date"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, verbose_name="Subscription enabled or not"
                    ),
                ),
                (
                    "catalog_status",
                    models.BooleanField(
                        default=False, verbose_name="Add to fonecta catalog"
                    ),
                ),
                (
                    "temp_close",
                    models.BooleanField(
                        default=False, help_text="Temporarily closed", null=True
                    ),
                ),
                (
                    "barring_international",
                    models.BooleanField(
                        default=False,
                        help_text="Barring international calls",
                        null=True,
                        verbose_name="Barring International",
                    ),
                ),
                (
                    "barring_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.barringdata",
                    ),
                ),
                (
                    "barring_mms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.barringmms",
                    ),
                ),
                (
                    "barring_roaming",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.barringroaming",
                    ),
                ),
                (
                    "barring_roamingdata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.barringroamingdata",
                    ),
                ),
                (
                    "barring_sms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.barringsms",
                    ),
                ),
                (
                    "barring_voice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.barringvoice",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.customer",
                    ),
                ),
                (
                    "mobile_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.mobileproduct",
                    ),
                ),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mobile.sim"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mobileproduct",
            name="dataspeed3GDown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dataspeed3Gdown",
                to="mobile.subscriptiondataspeed",
            ),
        ),
        migrations.AddField(
            model_name="mobileproduct",
            name="dataspeed3GUp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dataspeed3Gup",
                to="mobile.subscriptiondataspeed",
            ),
        ),
        migrations.AddField(
            model_name="mobileproduct",
            name="dataspeed4GDown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dataspeed4Gdown",
                to="mobile.subscriptiondataspeed",
            ),
        ),
        migrations.AddField(
            model_name="mobileproduct",
            name="dataspeed4GUp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dataspeed4Gup",
                to="mobile.subscriptiondataspeed",
            ),
        ),
        migrations.AddField(
            model_name="mobileproduct",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mobile.mobilepriority",
            ),
        ),
        migrations.AddField(
            model_name="mobileproduct",
            name="voicepackage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mobile.subscriptionvoicepackage",
            ),
        ),
        migrations.AddField(
            model_name="barringvoice",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
            ),
        ),
        migrations.AddField(
            model_name="barringsms",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
            ),
        ),
        migrations.AddField(
            model_name="barringroamingdata",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
            ),
        ),
        migrations.AddField(
            model_name="barringroaming",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
            ),
        ),
        migrations.AddField(
            model_name="barringmms",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
            ),
        ),
        migrations.AddField(
            model_name="barringdata",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mobile.carrier"
            ),
        ),
    ]
