# Generated by Django 4.1 on 2023-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sim",
            old_name="customer",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="customer",
            new_name="organization",
        ),
    ]
