# Generated by Django 4.1 on 2023-05-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0002_rename_customer_sim_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="sent_to_dna",
            field=models.BooleanField(
                default=False,
                help_text="Data send to dna api",
                verbose_name="Send to dna",
            ),
        ),
    ]
