# Generated by Django 4.1 on 2023-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0003_subscription_sent_to_dna"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Subscription soft delete",
                verbose_name="Subscription Delete",
            ),
        ),
    ]
