# Generated by Django 4.1 on 2023-07-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_subscription_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="catalogServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Street address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Postal code",
                    ),
                ),
                (
                    "sub_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.subscription",
                    ),
                ),
            ],
        ),
    ]
