# Generated by Django 4.1 on 2023-05-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dna", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssData",
        ),
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssDataRoamingLimit",
        ),
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssMms",
        ),
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssMobileVoice",
        ),
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssRoaming",
        ),
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssSms",
        ),
        migrations.RemoveField(
            model_name="serviceid",
            name="cfssSmsValueAddedServices",
        ),
        migrations.AddField(
            model_name="serviceid",
            name="cfsId",
            field=models.CharField(blank=True, max_length=256, verbose_name="cfsId"),
        ),
        migrations.AddField(
            model_name="serviceid",
            name="serviceId",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="serviceId"
            ),
        ),
    ]
