# Generated by Django 4.1.5 on 2023-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_alter_customer_reseller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
