# Generated by Django 4.1 on 2023-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobile", "0002_rename_customer_sim_organization_and_more"),
        ("users", "0002_rename_customer_seterauser_organization"),
        ("auditlog", "0002_rename_customer_log_organization"),
        ("organization", "0003_alter_customer_information"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Organization",
        ),
    ]
