# Generated by Django 4.1 on 2023-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_rename_customer_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="goodsign_org_identifier",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_sale_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_sale_agent_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_sale_reseller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_sale_reseller_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="odoo_org_identifier",
            field=models.IntegerField(default=0),
        ),
    ]
