# Generated by Django 4.1 on 2023-06-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_customer_seterauser_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="seterauser",
            name="mobile",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Mobile Number"
            ),
        ),
    ]
